### ISSUE TITLE
ddmrp_production_equivalent

### ISSUE THREAD

**Issue by max3903** [OCA/ddmrp#10]
This module will allow you to use equivalent products when creating a manufacturing order.

Odoo will assume that products in the same product category or subcategories are equivalent.

# Configuration

* Go to Manufacturing > Master Data > Products
* Create the following products:

Product | Priority | Product Category | Buffer Level (Netflow)
-- | -- | -- | --
Server | 10 | Servers | red
Part A | 10 | Parts | red
Part B | 20 | Parts/Sub 1 | red
Part C | 30 | Parts/Sub1/Sub2 | green
Part D | 40 | Parts/Sub1/Sub2/Sub3 | green
Part E | 50 | Parts | green
Part F | 20 | Office Supplies | green

* Go to Manufacturing > Master Data > Bill of Materials
* Create a BOM for 1 Server with:

Component | Quantity | Use Equivalences | Non-Equivalent Products
-- | -- | -- | --
Part A | 1 | True | Part C

# Usage

* Go to Manufacturing
* Create a manufacturing order for 15 Servers
* The manufacturing order will be consuming 15 Part D because:
  * Part A buffer is red
  * Part B is equivalent but the buffer is red
  * Part C is excluded
  * Part D has a higher priority than E
  * Part F is in a different product category

**Comment by LoisRForgeFlow** [comment]
related PR is merged.
