### ISSUE TITLE
ddmrp (or another dependency) disables scheduled actions or conflicts with another module to do this - v13 odoo.sh production

### ISSUE THREAD

**Issue by walkerblackwell** [OCA/ddmrp#156]
After install of DDMRP + of the base dependancies for DDMRP scheduled actions will not run or update their next-trigger date/time. They can run manually only. This is only apparent in production mode not test mode. Uninstalling DDMRP (v13) re-activates scheduled actions. I don't know where to hunt for the specific code that causes this error. A pointer on where to hunt would be good so I can give more info on the specifics and see if it's a conflict with another non-related module.

best regards,
Walker

**Comment by JordiBForgeFlow** [comment]
Try to deactivate the scheduled action https://github.com/OCA/ddmrp/blob/13.0/ddmrp/data/ir_cron.xml and see if the scheduled actions still work.

**Comment by walkerblackwell** [comment]
I did this post install and this did not fix the issue. I will remove the action from data entirely and re-install and see if this keeps the functionality.

Unfortunately it has to all be done in production instance (eek) to test the bug. Creating an odoo.sh staging of the "deactive-not-working" production machine actually gets schedulers working WITH the ddmrp installed. So something is up at a low level. Maybe ddmrp is hitting a memory limit on first run and pausing everything else?

best
Walker

**Comment by walkerblackwell** [comment]
I have isolated it to only DDMRP model (no dependancies) and not installing the cron data still disables scheduled actions in production environment in odoo.sh . . . staging environment does not disable scheduled actions so this is particular to a production environment setup. Maybe this is a post install hook problem . . .

**Comment by walkerblackwell** [comment]
I disable the hooks and the issue persists. I have-not (do not know how) found whatever class/function is disabling the cron scheduler . . . . a search of all code related to CRON brings up some python but I see nothing in there that is a monkey patch nor do I see anything that is giving an error. Ugh, was hoping to make this a core bit of our business. 

-Walker

**Comment by JordiBForgeFlow** [comment]
Walker are you using this module? https://github.com/OCA/ddmrp/tree/13.0/ddmrp_cron_actions_as_job. You should know that odoo.sh does not support the OCA queue job.

Looks to me that your issue is specific to your production installation, and I think that you should seek professional advice to get your DDMRP up and running.

**Comment by walkerblackwell** [comment]
Dear Jordi, yes I have contacted Odoo proper to see if they can investigate and also see some work on queue support with Odoo.sh.

https://github.com/EssentNovaTeam/queue/commit/e770a16fc98ced9b55a3f66cbed914b93b0f8924

Would you know the difference between jobs in staging vs production and why this would work in staging and not production?

best regards,
Walker

**Comment by JordiBForgeFlow** [comment]
They won't add any support of queue job into Odoo.sh. Several people has already tried that in the past. Odoo has been trying to build their own Queue implementation, without success so far.

I don't know upfront what would be the reason for this kind of different behaviour in staging vs. production.
