### ISSUE TITLE
Duplicate repo ? ddmrp-1

### ISSUE THREAD

**Issue by legalsylvain** [OCA/ddmrp#176]
Hi, I just knew, via twitter (https://twitter.com/OCA_Bot/status/1443980617843187730) that an new Oca repo was created : https://github.com/OCA/ddmrp-1

That seems a duplicate of the current ddmrp repo. Don't you think ? 

CC : @LoisRForgeFlow

Thanks.

**Comment by LoisRForgeFlow** [comment]
That is really weird, it is a fork of the original ForgeFlow/ddmrp repository, that is discontinued. It is safe to remove that fork from my POV.

@pedrobaeza do you have rights to do this (remove https://github.com/OCA/ddmrp-1)?

**Comment by pedrobaeza** [comment]
I'm not able. It should be someone from @OCA/board

**Comment by LoisRForgeFlow** [comment]
@max3903 maybe you could help here?

**Comment by simahawk** [comment]
@LoisRForgeFlow shall I do it?

**Comment by simahawk** [comment]
done

**Comment by LoisRForgeFlow** [comment]
Thanks
