### ISSUE TITLE
[15.0] Bokeh error when navigating to a buffer

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/ddmrp#224]
Affected versions: v15.

How to reproduce:
- Navigate to a buffer
![Peek 2022-03-31 13-13](https://user-images.githubusercontent.com/23449160/161042831-47869fc5-98ba-465c-8196-1a3818058d91.gif)

It is reproducible in runboat and using firefox or chromium based browsers.

cc @ChrisOForgeFlow

**Comment by ChrisOForgeFlow** [comment]
This issue can be solved by this PR:

https://github.com/OCA/web/pull/2162

**Comment by LoisRForgeFlow** [comment]
Fix merged, closing
