### ISSUE TITLE
stock_demand_estimate + adu calc

### ISSUE THREAD

**Issue by rousseldenis** [OCA/ddmrp#241]
@JordiBForgeFlow @LoisRForgeFlow 

We have a project that implements now features for stock demand computations and average daily usages.

As we want to move the logic to OCA and as I don't want to have duplicate functional modules, I want to know if we maybe want to converge developments.

We have currently stock demand estimate based on materialized view (with almost standard fields) that allows to collect data quite massively.

Then, I thought about extracting adu computation from ddmrp in a separate module.

This, in a 16.0 migration phase.

Do you think it could be a good approach ?

**Comment by rousseldenis** [comment]
I would maybe do a PR with our implementation in order to have a discussion basis

**Comment by JordiBForgeFlow** [comment]
@rousseldenis Stock Demand Estimates == Forecasts. 

As I understand you have a materialized view that will generate a forecast, right?

But there are many, many ways to generate a forecast.

The ADU computation is something that could well be implemented outside of DDMRP, but the way it's done in DDMRP is quite particular. I wouldn't think that could be a problem to have another module that calculates an ADU in a different way.

**Comment by rousseldenis** [comment]
> Stock Demand Estimates == Forecasts.

Oooh, ok (my ddmrp is very far :sweat_smile: ).

The thing is more an average daily usage computation. Actually, we use it to determine the product abc classification for stock location putaway.

**Comment by rousseldenis** [comment]
I think we will propose a module that compute daily usage.

Reading your code, it will be possible to plug into ddmrp (if some want to use them both), adding a past source and add it there :

https://github.com/OCA/ddmrp/blob/13.0/ddmrp/models/stock_buffer.py#L1178

**Comment by LoisRForgeFlow** [comment]
@rousseldenis that sounds good, don't hesitate to ping us in your proposal when you open the PR

**Comment by legalsylvain** [comment]
Very interested by such feature. Please ping me when some PR is available. 
Happy new years.

**Comment by CasVissers-360ERP** [comment]
I would also be interested in this module without having to get familiar with the whole DDMRP logic. We have similar set-ups to calculate min-max based on an A/B/C set-up based on WOC (weeks of coverage).
<img width="150" alt="image" src="https://user-images.githubusercontent.com/20641860/209289127-6ed59ff4-1d47-4aa8-b8c6-603fa87e1880.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/20641860/209289619-d37092d8-08ed-4274-b46e-32f907ecb8e4.png">

**Comment by larshalvoraam** [comment]
> > Stock Demand Estimates == Forecasts.
> 
> Oooh, ok (my ddmrp is very far 😅 ).
> 
> The thing is more an average daily usage computation. Actually, we use it to determine the product abc classification for stock location putaway.

ABC classification for stock putaway is recommended to be calculated by the number of movements in the warehouse.  And not by qty moved.   It is the number ov movements that are important for how much work is needed,

**Comment by rousseldenis** [comment]
@legalsylvain @JordiBForgeFlow @larshalvoraam @LoisRForgeFlow I made a first work there : https://github.com/OCA/stock-logistics-reporting/pull/257
