### ISSUE TITLE
need chinese language support

### ISSUE THREAD

**Issue by jeffery9** [OCA/ddmrp#27]

**Comment by JordiBForgeFlow** [comment]
Please go to https://translation.odoo-community.org/new-lang/ddmrp-11-0/ddmrp-11-0-ddmrp/ and start a new translation.

**Comment by jeffery9** [comment]
report  ```Permission Denied
Insufficient privileges to display this page.```

how can I request access for this project, and request new language.

**Comment by elicoidal** [comment]
use github login

**Comment by jeffery9** [comment]
login as github account.
no chinese language listed there, and not new language request also.

![image](https://user-images.githubusercontent.com/1404460/46750088-c3400880-cce9-11e8-8956-69b1b744957f.png)

**Comment by pedrobaeza** [comment]
@sbidoul it seems we still have the problem with the role being reset.

**Comment by JordiBForgeFlow** [comment]
@jeffery9 I can add the language for you for now.

What kind of chinese do you want to add?
![image](https://user-images.githubusercontent.com/7683926/47014677-437fc700-d14b-11e8-8a96-23b0000f0664.png)

**Comment by sbidoul** [comment]
Hi there,

The roles have not been reset. Problem is that @jeffery9 was not in any group.

I added @jeffery9 to the Chinese translators group. It should be ok now.

**Comment by jeffery9** [comment]
I'd want to add chinese translation for ddmrp, but can't found chinese language or request new language for chinese.  thanks.

**Comment by JordiBForgeFlow** [comment]
@jeffery9 you can now. Please try

**Comment by jeffery9** [comment]
can't found add new language  

![image](https://user-images.githubusercontent.com/1404460/47076145-a26b3c00-d230-11e8-97c2-88cb0d7150b9.png)

**Comment by HviorForgeFlow** [comment]
@jeffery9 I think you can create a new translation for ddmrp following this link: https://translation.odoo-community.org/new-lang/ddmrp-11-0/ddmrp-11-0-ddmrp/

**Comment by jeffery9** [comment]
Permission Denied
Insufficient privileges to display this page.

[cid:image001.png@01D46896.6EB3FEA0]

**Comment by sbidoul** [comment]
@jeffery9 I finally found the cause of problem. The Chinese translators group was not defined correctly. 

Can you try again?

@pedrobaeza one must not forget to choose access to "All projects" when defining new translator groups.

**Comment by pedrobaeza** [comment]
@sbidoul I usually do it, but maybe I forgot it in this one, sorry.

**Comment by LoisRForgeFlow** [comment]
@jeffery9 is it good to close this one?

**Comment by pengcao** [comment]
how to install ddmrp,thanks!

**Comment by pengcao** [comment]
how to install ddmrp in odoo?  thanks!

**Comment by LoisRForgeFlow** [comment]
No answer for a long time, closing.
