### ISSUE TITLE
[whish]restrict buffer can choose profile that it's type relate to pull rule's action

### ISSUE THREAD

**Issue by jeffery9** [OCA/ddmrp#28]
as you know, the item_type of  buffer profile is related with pull rule's action

| buffer profile item type |  pull rule action |
|---------------------------|------------------------------|
|manufactured                |    manufacture       |
|purchased                     |   buy                |
|distributed                    |    move              |

for example, Product A is enable route `Manufacture`, so the buffer profile only list  those item type is `manufactured`, this should very help choose the right profile, and use the right DLT.

**Comment by LoisRForgeFlow** [comment]
It's not that easy, a product can have both manufacture, and move rules and 2 buffers one manufactured in a location and another distributed in another one. Feel free to open a PR if you come with a a proper logic to do it.
