### ISSUE TITLE
V11 Issues NameError: name 'figure' is not defined

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/ddmrp#29]
ddmrp\models\stock_warehouse_orderpoint.py", line 179, in _compute_ddmrp_chart
    p = figure(plot_width=300, plot_height=400,
NameError: name 'figure' is not defined

**Comment by digitalliuzg** [comment]
trouble shooting
pip install bokeh==0.12.7

**Comment by LoisRForgeFlow** [comment]
that's it!
