### ISSUE TITLE
Unknown dependencies x 4

### ISSUE THREAD

**Issue by toddabraham** [OCA/ddmrp#31]
I have 4 unknown dependencies showing up: web_widget_bokeh_chart, mrp_multi_level, stock_warehouse_calendar, and base_cron_exclusion.

How do I install these?  I have tried installing web_widget_bokeh_chart from this link https://pypi.org/project/odoo11-addon-web-widget-bokeh-chart/ without luck.  

Can anyone guide my thinking on this?

**Comment by LoisRForgeFlow** [comment]
those modules are in other OCA repositories:
* https://github.com/OCA/web/tree/11.0/web_widget_bokeh_chart
* https://github.com/OCA/manufacture/tree/11.0/mrp_multi_level
* https://github.com/OCA/stock-logistics-warehouse/tree/11.0/stock_warehouse_calendar
* https://github.com/OCA/server-tools/tree/11.0/base_cron_exclusion
