### ISSUE TITLE
Unable to install module "web_widget_bokeh_chart" 

### ISSUE THREAD

**Issue by ferharo1** [OCA/ddmrp#33]
Hi,
I'm trying to install DDMRP in Odoo CE 11 on Ubuntu Server 18.04 LTS and appears this error:
Unable to install module "web_widget_bokeh_chart" because an external dependency is not met: No module named bokeh.
I already installed bokeh library and the error persist.

**Comment by LoisRForgeFlow** [comment]
A tip, always check documentation before asking: [web_widget_bokeh_chart 
REAMDE](https://github.com/OCA/web/tree/11.0/web_widget_bokeh_chart#installation)
