### ISSUE TITLE
enhancement in version 13

### ISSUE THREAD

**Issue by ghost** [OCA/ddmrp#48]
we'd suggest this enhancement in stock.buffer class for taking into account draft manufacturing order also:
    def _quantity_in_progress(self):
        """Return Quantities that are not yet in virtual stock but should
        be deduced from buffers (example: purchases created from buffers)"""
        res = dict(self.mapped(lambda x: (x.id, 0.0)))
        polines = self.env["purchase.order.line"].search(
            [
                ("state", "in", ("draft", "sent", "to approve")),
                ("buffer_ids", "in", self.ids),
            ]
        )
        for poline in polines:
            for buffer in poline.buffer_ids:
                res[buffer.id] += poline.product_uom._compute_quantity(
                    poline.product_qty, buffer.product_uom, round=False
                )

        morders = self.env["mrp.production"].search(
            [
                ("state", "=", "draft"),
                ("buffer_id", "in", self.ids),
            ]
        )
        for morder in morders:
            res[morder.buffer_id.id] += morder.product_uom_id._compute_quantity(
                morder.product_qty, morder.buffer_id.product_uom, round=False
            )
        return res

regards

**Comment by JordiBForgeFlow** [comment]
When manufacturing orders are created from stock buffers they are automatically confirmed. Therefore this case should not really occur.

**Comment by ghost** [comment]
sorry, you are right!
anyway, somehow it is important for products with multiple boms to create manufacturing orders in draft status.
in method
class StockRule(models.Model):
    _inherit = "stock.rule"

    @api.model
    def _run_manufacture(self, procurements):

we need to throw away the statement productions.action_confirm()

Regards
