### ISSUE TITLE
17.0 branch CI failing

### ISSUE THREAD

**Issue by henrybackman** [OCA/ddmrp#497]
17.0 branch tests are failing:
[https://github.com/OCA/ddmrp/actions/runs/11780101284/job/33190654835](https://github.com/OCA/ddmrp/actions/runs/11780101284/job/33190654835)

**Comment by LoisRForgeFlow** [comment]
Did you investigate what could have changed that made this start failing?

**Comment by henrybackman** [comment]
I've found that this commit causes the failing test:
- https://github.com/odoo/odoo/commit/1ed6dbeae531dff07a16d50457a16c51db184e40

**Comment by LoisRForgeFlow** [comment]
Hi @henrybackman 

Yes, indeed, we also found that culprit and open a PR/issue to discuss with Odoo https://github.com/odoo/odoo/pull/188846

**Comment by LoisRForgeFlow** [comment]
Fixed with a temporary patch via https://github.com/OCA/ddmrp/pull/500
